proxy:
  enabled: true
  protocol: http
  host: web-proxy.austin.hp.com
  port: 8080

encode: UTF-8

book:
  name: novel
  endpoint: https://m.mxzw.com/wapbook/111242/ # index page
  dir_point: div#chapterlist p a # css selector for chapter item on index page
  title_point: header#top span.title # css selector for chapter title on chapter page
  article_point: div#chaptercontent # css selector for chapter content

downloadFolder: /download
