proxy:
  enabled: true
  protocol: http
  host: web-proxy.austin.hp.com
  port: 8080

encode: UTF-8

book:
  name: novel
  endpoint: https://m.mxzw.com/wapbook/111242.html
  dir_point: div#chapterlist p a
  title_point: header#top + span
  article_point: div#chaptercontent
