proxy:
  enabled: true
  protocol: http
  host: web-proxy.austin.hp.com
  port: 8080

encode: UTF-8

book:
  name: novel
  endpoint: https://www.maopaoke.com/chapter/274441/
  dir_point: .chapterList li
  title_point: div.m-read-content h3
  article_point: div.m-read-content div div
